# Generated by Django 4.0.5 on 2022-06-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='TodoList',
        ),
    ]
